# Generated by Django 4.1.3 on 2022-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTaxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='vehiculo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('Fiat Siena', 'Fiat Siena'), ('Fiat Cronos', 'Fiat Cronos'), ('Volkswagen Voyage', 'Volkswagen Voyage'), ('Chevrolet Corsa', 'Chevrolet Corsa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Negro', 'Negro'), ('Gris', 'Gris')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=7),
        ),
    ]
